name: Lint nf-neuro component

on:
  workflow_dispatch:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: choice
        options:
          - module
          - subworkflow
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"
  workflow_call:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: string
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"

run-name: Lint ${{ inputs.component }}
jobs:
  nf-core-lint:
    runs-on: ubuntu-latest
    name: lint - ${{ inputs.component }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.10"

      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: "1.8.5"
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install nf-core tools and documentation utilities
        run: |
          poetry install --no-interaction --extras docs

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup nextflow
        uses: nf-core/setup-nextflow@561fcfc7146dcb12e3871909b635ab092a781f34 # v2.0.0
        with:
          version: ${{ inputs.nextflow_version }}

      - name: Lint ${{ inputs.type }} ${{ inputs.component }}
        env:
          GIT_CLONE_PROTECTION_ACTIVE: false
          NFCORE_MODULES_GIT_REMOTE: https://github.com/${{ github.repository }}.git
          NFCORE_SUBWORKFLOWS_GIT_REMOTE: https://github.com/${{ github.repository }}.git
          NFCORE_MODULES_BRANCH: main
          NFCORE_SUBWORKFLOWS_BRANCH: main
        run: poetry run nf-core --verbose ${{ inputs.type }}s lint ${{ inputs.component }}

      - name: Convert component meta.yml to markdown
        run: |
          poetry run nf-neuro-convert-${{ inputs.type }} \
            --enhance-keywords \
            ${{ inputs.type }}s/nf-neuro/${{ inputs.component }} \
            ${{ github.sha }} \
            $(echo "${{ inputs.component }}" | sed 's/\//_/g').md
